### ISSUE TITLE
Adaptation for image sequences?

### ISSUE THREAD

**Issue by laurazpm** [moziada/Moving-Objects-Segmentation#1]
Hello! 

Great job here, really useful. In my case, I'd like to implement it using an image sequence, I've tried it also with OpenCV's VideoCapture but I can't make it work, do you have any ideas?

Thank you!
Laura

**Comment by moziada** [comment]
I think it would be a minor change on the existing method that uses a video sequence, reading an image sequence would go like this:
```
img_names = os.listdir(input_path)
for frame_num, img_name in enumerate(img_names):
    img_path = os.path.join(input_path, img_name)
    frame = cv2.imread(img_path)
    if frameNum % skipping == 0:
                frames.append(frame)
                num_of_memorized_frames += 1
    if num_of_memorized_frames = memorize:
        break
```
please contact me if it worked for you

**Comment by laurazpm** [comment]
I've just a chance to try it and it worked perfectly, thank you!!
